#ifndef __ENUM_NONT_H__
#define __ENUM_NONT_H__

enum nonT {
    PROG ,
    DECLLIST ,
    DECLSTMT ,
    PROCDECLLIST ,
    PROCDECL ,
    DATATYPE ,
    ARRAYNONT ,
    STMTLIST ,
    SUPERSTMT ,
    LABELSTMT ,
    POSTLABELSTMT ,
    STMT ,
    LABELLESSSTMT ,
    POSTLABELLESSSTMT ,
    IDLESSSTMT ,
    CONTROLSTMT ,
    IFSTMT ,
    ELSE1 ,
    GOTOSTMT ,
    LOOPSTMT ,
    EXITSTMT ,
    STOPSTMT ,
    IOSTMT ,
    SKIPNONT ,
    ATTRSTMT ,
    PROCSTMT ,
    SUPERIDLIST ,
    IDLIST ,
    IDLIST2 ,
    EXPRLIST ,
    EXPRLISTTAIL ,
    E   ,
    E_  ,
    A   ,
    T   ,
    T_  ,
    B   ,
    T2	,
    T2_	,
    C 	,
    T3	,
    T3_	,
    D 	,
    F 	,
    LITERAL,
    NONTENUMSIZE
};

const char* nontNames[] = {
    "PROG" ,
    "DECLLIST" ,
    "DECLSTMT" ,
    "PROCDECLLIST" ,
    "PROCDECL" ,
    "DATATYPE" ,
    "ARRAYNONT" ,
    "STMTLIST" ,
    "SUPERSTMT" ,
    "LABELSTMT" ,
    "POSTLABELSTMT" ,
    "STMT" ,
    "LABELLESSSTMT" ,
    "POSTLABELLESSSTMT" ,
    "IDLESSSTMT" ,
    "CONTROLSTMT" ,
    "IFSTMT" ,
    "ELSE1" ,
    "GOTOSTMT" ,
    "LOOPSTMT" ,
    "EXITSTMT" ,
    "STOPSTMT" ,
    "IOSTMT" ,
    "SKIPNONT" ,
    "ATTRSTMT" ,
    "PROCSTMT" ,
    "SUPERIDLIST" ,
    "IDLIST" ,
    "IDLIST2" ,
    "EXPRLIST" ,
    "EXPRLISTTAIL" ,
    "E"   ,
    "E_"  ,
    "A"   ,
    "T"   ,
    "T_"  ,
    "B"   ,
    "T2"  ,
    "T2_" ,
    "C"   ,
    "T3"  ,
    "T3_" ,
    "D"   ,
    "F"   ,
    "LITERAL"
};

#endif