#ifndef __RECURSIVE_DESCENT__
#define __RECURSIVE_DESCENT__

void STMT();
void CONTROLSTMT();
void IDLESSSTMT();
void POSTLABELESSSTMT();
void IDLESSSTMT();
void STARTTOK();
void TERMINATORTOK();
void POSTLABELSTMT ();
void LABELLESSTMT();
void STMT();
void LPARENTOK();
void RPARENTOK();
void DECLARETOK();
void ENDTOK();
void IDENTIFIERTOK();
void COMMATOK();
void DATATYPETOK();
void PROCEDURETOK();
void EXPRLIST();
void EXPRLISTTAIL();
void E();
void E_();
void A();
void T();
void T_();
void B();
void T2();
void ARRAYTOK();
void DATATYPENONT();
void IDLIST2();
void IDLIST();
void DECLSTMT();
void DECLSTMTLIST();
void PROCDECLLIST();
void PROCDECL();
void LABELSTMT();
void SUPERSTMT();
void STMTLIST();
void IFTOK();
void ELSETOK();
void ELSESTMT();
void GOTOTOK();
void GOTOSTMT();
void LOOPTOK();
void EXITWHENTOK();
void EXITSTMT();
void SKIPTOK();
void SKIPSTMT();
void STOPTOK();
void STOPSTMT();
void PROGRAM();

#endif